print ('Welcome to python programming')

print ('Enter your name: ')
Myname = input()
print ('Hello Mr' + Myname + 'Welcome')
print ('Enter your Age: ')
Myage = input()
print('your age will be ' + str(int(Myage)+2) + ' in 2020')
print('The length of your name is:')
print(len(Myname))
